root = "."
tmp_dir = "tmp"

[build]
pre_cmd = ["cd cmd/db && sqlc generate", "templ generate", "yarn build"]
cmd = "go build -o ./tmp/main cmd/*.go"
exclude_dir = ["tmp", "esp32", "node_modules", ".yarn", ".git", "static/css"]
exclude_regex = ["_test.go", "cmd/db/.*go", "_templ.go"]
full_bin = "JWT_SECRET=jwt_secret ./tmp/main"
include_dir = ["cmd", "views", "pkg"]
include_ext = ["go", "html", "templ", "sql"]
log = "build-errors.log"
send_interrupt = true
stop_on_error = true
delay = 0
