version: "3"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gate
    volumes:
      - ./cmd/services/db/schema.sql:/docker-entrypoint-initdb.d/init.sql
  gate:
    build: .
    ports:
      - 8081:80
    image: wood-wood-gate
    environment:
      GATE_SECRET: woody_wood_secret
