version: "3"
services:
  db:
    image: postgres
    ports:
      - 8080:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gate
    volumes:
      - ./data:/var/lib/postgresql/data
  gate:
    build: .
    ports:
      - 8081:80
    image: wood-wood-gate
    environment:
      GATE_SECRET: woody_wood_secret
