// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Log struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID             pgtype.UUID
	Email          string
	FullName       string
	Apartment      string
	PwdSalt        string
	PwdHash        string
	PwdIterations  int32
	PwdParallelism int16
	PwdMemory      int32
	PwdVersion     int32
	Role           string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}
